import * as v1 from "./agent_v1";
import * as v2 from "./agent_v2";

export type PromptPack = typeof v2;

const packs: Record<string, PromptPack> = {
  agent_v1: v1 as unknown as PromptPack,
  agent_v2: v2,
};

export function getActivePromptVersion(): string {
  return process.env.AGENT_PROMPT_VERSION || "agent_v2";
}

export function getActivePrompts(): PromptPack {
  const key = getActivePromptVersion();
  return packs[key] ?? v2;
}

export const {
  PROMPT_VERSION,
  ANALYST_SYSTEM_PROMPT,
  STRATEGIST_SYSTEM_PROMPT,
  STRATEGIST_USER_PREFIX,
  STRATEGIST_PERSONA_SUPPLY_CHAIN,
  STRATEGIST_PERSONA_FINANCIAL,
  STRATEGIST_PERSONA_LOGISTICS,
  ROUTE_PLANNER_SYSTEM_PROMPT,
  ROUTE_PLANNER_JSON_HINT,
  ROUTE_PLANNER_USER_HINT,
  appendUserConstraint,
  STRATEGIST_RETRY_HINT,
  AGENT_INSIGHT_TOOL_HINT,
  AGENT_INSIGHT_JSON_HINT,
} = (() => {
  const p = getActivePrompts();
  return {
    PROMPT_VERSION: p.PROMPT_VERSION,
    ANALYST_SYSTEM_PROMPT: p.ANALYST_SYSTEM_PROMPT,
    STRATEGIST_SYSTEM_PROMPT: p.STRATEGIST_SYSTEM_PROMPT,
    STRATEGIST_USER_PREFIX: p.STRATEGIST_USER_PREFIX,
    STRATEGIST_PERSONA_SUPPLY_CHAIN: p.STRATEGIST_PERSONA_SUPPLY_CHAIN,
    STRATEGIST_PERSONA_FINANCIAL: p.STRATEGIST_PERSONA_FINANCIAL,
    STRATEGIST_PERSONA_LOGISTICS: p.STRATEGIST_PERSONA_LOGISTICS,
    ROUTE_PLANNER_SYSTEM_PROMPT: p.ROUTE_PLANNER_SYSTEM_PROMPT,
    ROUTE_PLANNER_JSON_HINT: p.ROUTE_PLANNER_JSON_HINT,
    ROUTE_PLANNER_USER_HINT: p.ROUTE_PLANNER_USER_HINT,
    appendUserConstraint: p.appendUserConstraint,
    STRATEGIST_RETRY_HINT: p.STRATEGIST_RETRY_HINT,
    AGENT_INSIGHT_TOOL_HINT: p.AGENT_INSIGHT_TOOL_HINT,
    AGENT_INSIGHT_JSON_HINT: p.AGENT_INSIGHT_JSON_HINT,
  };
})();
